VEOSS-595 | Added validation for correction amount
hmrc/one-stop-shop-returns-frontend pull request #162
Opened 2021-11-22 11:28 UTC by owen-opencast

Also including content from [VEOSS-666.](https://jira.tools.tax.service.gov.uk/browse/VEOSS-666)

2021-11-22 13:55 UTC, darbyo requested changes

2021-11-22 13:55 UTC, darbyo commented on test/controllers/corrections/CountryVatCorrectionControllerSpec.scala
> +//      when(mockService.getLatestVatAmountForPeriodAndCountry(any(), any())(any(), any())) thenReturn Future.successful(validAnswer)
Do we need these mocks? If not can delete the comments

2021-11-22 15:34 UTC, owen-opencast commented on app/controllers/corrections/CountryVatCorrectionController.scala
> +            val form = formProvider(country.name, -vatOwedToCountryOnPrevReturn)
We could, we'd need to add a custom validator to checking of that form. We'd also still need to do -vatOwedToCountryOnPrevReturn in the form provider, to get the error message in the format specified (e.g. "The correction value must be more than £-300" - the inverse of the current VAT owed). Can do it if you want to?

2021-11-22 16:14 UTC, darbyo commented on app/controllers/corrections/CountryVatCorrectionController.scala
> +            val form = formProvider(country.name, -vatOwedToCountryOnPrevReturn)
I think we should go for the more readable solution. But will leave the decision up to you guys, I think this way isnt totally obvious what is happening until you dig down inside it, however it is correct. If yous dont want to make that change, can we at least pull '-vatOwedToCountryOnPrevReturn' out to a variable named such as 'minimumAmount' or something nicely descriptive

2021-11-23 10:18 UTC, owen-opencast commented on app/controllers/corrections/CountryVatCorrectionController.scala
> +            val form = formProvider(country.name, -vatOwedToCountryOnPrevReturn)
I've added pulled it out to a new variable, I think it's clearer now!

2021-11-23 17:07 UTC, darbyo approved these changes

2021-11-25 11:08 UTC, merged