VEOSS-1816 Alter Dashboard Variations for Excluded Traders
hmrc/one-stop-shop-returns-frontend pull request #305
Opened 2024-05-16 04:18 UTC by ZDevelop94

- Needs Removal of optional `effectiveDate` in `ExcludedTrader` in registration backend to be merged.

2024-05-16 10:00 UTC, DevAndyroo requested changes

2024-05-16 10:00 UTC, DevAndyroo commented on app/views/IndexView.scala.html
> +                    @if(excludedTrader.exclusionReason == 4) {
if we could use the enum here as well, might be better. I'd be open for you to change the backend to provide it as an enum as well, over an int

2024-05-16 10:06 UTC, ZDevelop94 commented on app/services/PartialReturnPeriodService.scala
> +        val hmrcExclusionReason = 6
Yeah I created enums i will use them

2024-05-17 09:44 UTC, DevAndyroo requested changes

2024-05-17 09:44 UTC, DevAndyroo commented on app/views/IndexView.scala.html
> +                            <p class="govuk-body">@messages("yourAccount.finalReturn.message")</p> //here
one last one

2024-05-17 10:19 UTC, ZDevelop94 commented on app/views/IndexView.scala.html
> +                            <p class="govuk-body">@messages("yourAccount.finalReturn.message")</p> //here
Weird not on my one refresh?

2024-05-17 12:25 UTC, merged