VEOSS-389: Previous Return Page
hmrc/one-stop-shop-returns-frontend pull request #59
Opened 2021-09-06 14:00 UTC by DevAndyroo

2021-09-06 15:36 UTC, darbyo requested changes

2021-09-06 15:36 UTC, darbyo commented on app/controllers/PreviousReturnController.scala
> +          Redirect(routes.IndexController.onPageLoad()) // TODO
//TODO ? Is there something to do here or should the comment be removed?

2021-09-06 15:36 UTC, darbyo commented on app/viewmodels/previousReturn/PreviousReturnSummary.scala
> +    None
Do we need this?

2021-09-07 08:57 UTC, DevAndyroo commented on app/viewmodels/previousReturn/PreviousReturnSummary.scala
> +    None
No, placeholder for when we do

2021-09-07 09:11 UTC, warrenskiwork1979 approved these changes

2021-09-07 09:11 UTC, merged